# version: "3"

# services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - "5436:5432"
#     environment:
#       POSTGRES_PASSWORD: pass123

version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            # DATABASE_URL: postgres://user:password@postgres:5436/db
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:10.4
        ports:
          - "5436:5432"
        environment: 
          POSTGRES_PASSWORD: pass123
